export const API_URL = process.env.REACT_APP_API || 'http://localhost:3000/'

export const HOME_URL = '/'
export const LOGIN_URL = '/login'
export const LOGOUT_URL = '/logout'
export const CREATE_PROPERTY_URL = '/become-a-dihauser'
export const USER_REGISTRER_URL = '/user/register'
export const CONTACT_PROPERTY_URL = '/contact_hauser/:id'
export const HAUSER_BOOKING_LIST_URL = '/user/:id/booking-list'
export const BOOKING_PROPERTY_URL = '/booking_id/:id'
export const USER_MESSAGES_URL = '/user/inbox/:id'
export const USER_PROFILE_URL = '/user/:id'
export const USER_COMMENTS_URL = '/user/:id/comments'
export const DETAIL_PROPERTY_URL = '/home/:id'
export const PROPERTY_LOCATION_URL = '/:location/homes'